[project]
name = "genesis_core"
description = "Genesis Core services"
readme = "README.md"
authors = [{name = "Genesis Corporation", email = "eugene@frolov.net.ru"}]
dynamic = ["version"]
license = {text = "Apache-2.0"}
requires-python = ">=3.8"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
[project.urls]
homepage = "https://github.com/infraguys/genesis_core/"

[build-system]
requires = [
    "setuptools>=75.3.3",  # last version for python3.8
    "setuptools_scm>=8"
]
build-backend = "setuptools.build_meta"

dependencies = [
    "pbr>=1.10.0,<5.8.2",  # Apache-2.0
    "oslo.config>=3.22.2,<10.0.0",  # Apache-2.0
    "bjoern>=3.2.2",  # BSD License (BSD-3-Clause)
    "gcl_looper>=1.0.1,<2.0.0",  # Apache-2.0
    "restalchemy>=15.0.1,<16.0.0",  # Apache-2.0
    "libvirt-python>=11.0.0,<12.0.0",  # GNU Lesser General Public License v2 or later (LGPLv2+)
    "Authlib>=1.3.2,<2.0.0",  # BSD License (BSD-3-Clause)
    "bazooka>=1.3.0,<2.0.0",  # Apache-2.0
    "Jinja2>=3.1.5,<4.0.0",  # BSD License (BSD-3-Clause)
    "izulu>=0.50.0,<1.0.0",  # MIT License
    "gcl_iam>=1.0.3,<2.0.0",  # Apache-2.0
    "gcl_sdk>=1.4.1,<2.0.0",  # Apache-2.0
    "gcl_certbot_plugin>=0.0.5,<1.0.0",  # Apache-2.0
    "pyotp>=2.9.0,<3.0.0",  # MIT License
    "pyyaml>=6.0.0,<7.0.0",  # MIT
    "netaddr>=1.3.0,<2.0.0",  # BSD License (BSD License)
    "cryptography>=45.0.5,<47.0.0",  # BSD-3
    "firebase-admin>=6.0.0,<7.0.0",  # Apache-2.0
    "altcha>=0.2.0,<0.3.0; python_version >= \"3.9\"",  # MIT License
    "altcha<0.2.0; python_version < \"3.9\"",  # MIT License
]

[project.optional-dependencies]
base = [
    "pbr>=1.10.0,<5.8.2",  # Apache-2.0
    "oslo.config>=3.22.2,<10.0.0",  # Apache-2.0
    "bjoern>=3.2.2",  # BSD License (BSD-3-Clause)
    "gcl_looper>=1.0.1,<2.0.0",  # Apache-2.0
    "restalchemy>=15.0.1,<16.0.0",  # Apache-2.0
    "libvirt-python>=11.0.0,<12.0.0",  # GNU Lesser General Public License v2 or later (LGPLv2+)
    "Authlib>=1.3.2,<2.0.0",  # BSD License (BSD-3-Clause)
    "bazooka>=1.3.0,<2.0.0",  # Apache-2.0
    "Jinja2>=3.1.5,<4.0.0",  # BSD License (BSD-3-Clause)
    "izulu>=0.50.0,<1.0.0",  # MIT License
    "gcl_iam>=1.0.3,<2.0.0",  # Apache-2.0
    "gcl_sdk>=1.4.1,<2.0.0",  # Apache-2.0
    "gcl_certbot_plugin>=0.0.5,<1.0.0",  # Apache-2.0
    "pyotp>=2.9.0,<3.0.0",  # MIT License
    "pyyaml>=6.0.0,<7.0.0",  # MIT
    "netaddr>=1.3.0,<2.0.0",  # BSD License (BSD License)
    "cryptography>=45.0.5,<47.0.0",  # BSD-3
    "firebase-admin>=6.0.0,<7.0.0",  # Apache-2.0
    "altcha>=0.2.0,<0.3.0; python_version >= \"3.9\"",  # MIT License
    "altcha<0.2.0; python_version < \"3.9\"",  # MIT License
]
dev = [
    "tox>=4.0.0",
    "tox-uv",
    "pytest>=7.0.0",
]
test = [
    "coverage>=4.0",
    "mock>=3.0.5,<4.0.0",  # BSD
    "pytest>=8.0.0,<9.0.0",  # MIT License (MIT)
    "pytest-xdist[psutil]>=3.6.1,<4.0.0",  # MIT License (MIT)
    "pytest-timer>=1.0.0,<2.0.0",  # MIT License (MIT)
]
mypy = [
    "mypy",
]
ruff = [
    "ruff",
]
shellcheck = [
    "shellcheck-py",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "docs",
]

# Same as Black.
line-length = 88
indent-width = 4
# Assume Python 3.8
target-version = "py38"
[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.setuptools.packages.find]
where = ["."]

[project.scripts]
gc-user-api = "genesis_core.cmd.user_api:main"
gc-orch-api = "genesis_core.cmd.orch_api:main"
gc-status-api = "genesis_core.cmd.status_api:main"
gc-gservice = "genesis_core.cmd.gservice:main"
gc-core-agent = "genesis_core.cmd.core_agent:main"
gc-bootstrap = "genesis_core.cmd.bootstrap:main"
gc-manifest-parser = "genesis_core.cmd.manifest_parser:main"

[project.entry-points."gcn_machine_pool_driver"]
DummyPoolDriver = "genesis_core.compute.pool.drivers.base:DummyPoolDriver"
libvirt = "genesis_core.compute.pool.drivers.libvirt:LibvirtPoolDriver"

[project.entry-points."gcn_network_driver"]
DummyNetworkDriver = "genesis_core.network.driver.base:DummyNetworkDriver"
FlatBridgeNetworkDriver = "genesis_core.network.driver.flat:FlatBridgeNetworkDriver"

[project.entry-points."gcl_sdk_event_payloads"]
IamUserRegistration = "genesis_core.events.payloads:RegistrationEventPayload"
IamUserResetPassword = "genesis_core.events.payloads:ResetPasswordEventPayload"

[project.entry-points."gcl_sdk_universal_agent"]
PasswordCapabilityDriver = "genesis_core.agent.universal.drivers.secret.password:PasswordCapabilityDriver"
CoreDNSCertificateCapabilityDriver = "genesis_core.agent.universal.drivers.secret.cert:CoreDNSCertificateCapabilityDriver"

[tool.uv]
package = true

[tool.mypy]
exclude = [
    '.venv',
    'genesis_core/tests',
]
python_version = "3.12"
disallow_untyped_defs = true
show_error_codes = true
no_implicit_optional = true
warn_return_any = false
warn_unused_ignores = true
ignore_missing_imports = true

[tool.setuptools.package-data]
genesis_core = ["*.yaml", "*.md"]

[tool.coverage.run]
branch = true
source = [
    "genesis_core"
]
command_line = "-m pytest -s genesis_core/tests/functional"
omit = [
    "genesis_core/tests/*",
    ".venv",
    "memory:0x"
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",
    "if settings\\.DEBUG",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    "if TYPE_CHECKING:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    ]

ignore_errors = true

[tool.coverage.html]
directory = "cover"


[tool.coverage.xml]
output = "cover/coverage.xml"